# Generated by Django 6.0.4 on 2026-05-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pages.lecture'),
        ),
        migrations.AlterField(
            model_name='pset',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psets', to='pages.lecture'),
        ),
    ]
