# Generated by Django 6.0.4 on 2026-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_note_lecture_alter_pset_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
