# Generated by Django 6.0.4 on 2026-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_lecture_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pset',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pset',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pset',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pset',
            constraint=models.UniqueConstraint(fields=('lecture', 'order'), name='unique_pset_order_per_lecture'),
        ),
    ]
