# Generated by Django 6.0.4 on 2026-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_lecture_options_alter_pset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pset',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
