# Generated by Django 6.0.4 on 2026-05-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_note_note_alter_pset_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='note',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='pages.lecture'),
        ),
    ]
