# Generated by Django 6.0.4 on 2026-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_note_note_text_alter_note_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
