# Generated by Django 6.0.4 on 2026-05-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pset_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('tips', models.TextField(null=True)),
                ('start', models.TextField(null=True)),
                ('test', models.TextField(null=True)),
                ('sumbit', models.TextField(null=True)),
                ('pset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.pset')),
            ],
        ),
    ]
