# Generated by Django 6.0.4 on 2026-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_psetdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psetdescription',
            name='start',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='sumbit',
        ),
        migrations.AddField(
            model_name='psetdescription',
            name='check_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='psetdescription',
            name='ffile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psetdescription',
            name='submit',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='psetdescription',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psetdescription',
            name='test',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psetdescription',
            name='tips',
            field=models.TextField(blank=True),
        ),
    ]
