# Generated by Django 6.0.4 on 2026-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_psetdescription_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psetdescription',
            name='ffile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
