# Generated by Django 6.0.4 on 2026-05-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_psetdescription_ffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psetdescription',
            name='check_url',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='ffile',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='submit',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='test',
        ),
        migrations.RemoveField(
            model_name='psetdescription',
            name='tips',
        ),
        migrations.AddField(
            model_name='pset',
            name='check_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='ffile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pset',
            name='submit',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='test',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='tips',
            field=models.TextField(blank=True),
        ),
    ]
