# Generated by Django 6.0.4 on 2026-05-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_psetdescription_check_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PsetDescription',
        ),
    ]
