# Generated by Django 6.0.4 on 2026-05-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_delete_psetdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pset',
            old_name='tips',
            new_name='hint',
        ),
    ]
