# Generated by Django 6.0.4 on 2026-05-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_tips_pset_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pset',
            name='ffile',
        ),
        migrations.RemoveField(
            model_name='pset',
            name='text',
        ),
        migrations.AlterField(
            model_name='pset',
            name='check_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pset',
            name='submit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
