# Generated by Django 6.0.4 on 2026-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_pset_ffile_remove_pset_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='ascii',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
