# Generated by Django 6.0.4 on 2026-05-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_pset_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='begin_end',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='begin_start',
            field=models.TextField(blank=True),
        ),
    ]
