# Generated by Django 6.0.4 on 2026-05-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_pset_begin_end_pset_begin_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pset',
            old_name='begin_end',
            new_name='before_end',
        ),
        migrations.RenameField(
            model_name='pset',
            old_name='begin_start',
            new_name='before_start',
        ),
        migrations.AddField(
            model_name='pset',
            name='test_etc',
            field=models.TextField(blank=True),
        ),
    ]
