# Generated by Django 6.0.4 on 2026-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_begin_end_pset_before_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='topics',
            field=models.TextField(null=True),
        ),
    ]
