# Generated by Django 6.0.4 on 2026-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_lecture_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='cite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pset',
            name='demo_start',
            field=models.TextField(blank=True),
        ),
    ]
