# Generated by Django 6.0.4 on 2026-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_pset_cite_pset_demo_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
