# Generated by Django 6.0.4 on 2026-05-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_pset_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pset',
            name='check_url',
        ),
        migrations.RemoveField(
            model_name='pset',
            name='submit',
        ),
    ]
