# Generated by Django 6.0.4 on 2026-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_pset_check_url_remove_pset_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
